[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[line_break]
disabled = true

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Set 'foo' as custom color palette
palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'




[git_branch]
symbol = '🌱 '
truncation_length = 4
truncation_symbol = ''
ignore_branches = ['master', 'main']

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[helm]
format = 'via [⎈ $version](bold white) '

[container]
format = '[$symbol \[$name\]]($style) '

[c]
format = 'via [$name $version]($style)'

[docker_context]
format = 'via [🐋 $context](blue bold)'

[rust]
format = 'via [⚙️ $version](red bold)'